package mini.integration.customerservice.application.command.handler;

import mini.integration.customerservice.application.command.CustomerNotificationChannelConfigCommand;
import mini.integration.customerservice.infrastructure.dto.CustomerNotificationChannelConfigDTO;
import mini.integration.customerservice.lib.CommandHandler;

public interface CustomerNotificationChannelConfigCommandHandler extends CommandHandler<CustomerNotificationChannelConfigCommand, CustomerNotificationChannelConfigDTO> {
}
