classDiagram

    EntityBased <|-- Customer 
    Customer --> Contact
    Customer --> Address
    Customer ..> MemberShipPolicy
    Customer "1" --> "1" DailyPostedBalance
    Customer "1" --> "*" FileInfo
    
    CustomerDAO --> Customer
    FileInfoDAO --> FileInfo

    CustomerQueryService --> CustomerDAO
    FileInfoQueryService --> FileInfoDAO

    CustomerCommandService --> CustomerDAO
    FileInfoCommandService --> FileInfoDAO    

    CustomerQueryController --> CustomerQueryService
    FileInfoQueryController --> FileInfoQueryService

    namespace Domain {
    
        class EntityBased {
            - Integer seq
            - UUID id
            - OffsetDateTime createdDate
            - OffsetDateTime lastModifiedDate
            - String createdBy
            - String lastModifiedBy
        }

        class MemberShipType {
            <<Enum>>
            BRONZE,
            SILIVER,
            GOLD,
            PLATINUM

        }

        class MemberShipPolicy {         
            - MemberShipType: MemberShipType
            - requiredBalance: BigDecimal
            - requiredLoyaltyYear: int
            - List<MembershipPolicy> memberShipPolicies = List.of(
                 MembershipPolicy[BRONZE, BigDecimal.ZERO, 0],
                 MembershipPolicy[SILVER,  "10000", 2],
                 MembershipPolicy[GOLD,  "20000", 5],
                 MembershipPolicy[PLATINUM,  "50000", 8]
            );

            - evaluateMemberShip(postedBalance: BigDecimal, registedDate: OffsetDateTime): MemberShipLevel
        }

        class DailyPostedBalance {
            <<ValueObject>>
            - customer: Customer
            - dailyPostedBalance: BigDecimal
            - registeredDate: OffsetDateTime
        }


        class Customer {
            <<Entity>>

            - String firstName
            - String lastName
            - Gender gender
            - String description
            - Contact contact
            - Address address
            - Set<FileInfo> fileInfo
            - DailyPostedBalance dailyPostedBalance;
            

            evaluateMemberShip(): void


        }

        class Contact {
            <<ValueObject>>
            - String phone
            - String email
        }


        class Address {
            <<ValueObject>>
            - String line
            - String city
            - String state
            - String zipCode
        }    

        class Gender {
            <<Enum>>
            MALE
            FEMALE
        }

        class FileInfo {
            <<Entity>>
            - Integer seq
            - UUID fileKey
            - String fileName
            - String extension
            - number fileSize
        }
    }

    namespace Repository {
            class CustomerDAO { }
            class FileInfoDAO { }
    }

    namespace QueryService {
            class CustomerQueryService { }
            class FileInfoQueryService { }
    }

    namespace CommandService {
            class CustomerCommandService { }
            class FileInfoCommandService { }
    }

    namespace QueryController {
            class CustomerQueryController { }
            class FileInfoQueryController { }
    }

    namespace CommandController {
            class CustomerCommandController { }
            class FileInfoCommandController { }
    }
