---
title: Edit Customer Profile
---
sequenceDiagram
    autonumber
    actor c as Customer
    participant api as ApiGateway    


    participant cs as CustomerService    
    participant csCont as CommandController
    participant csServ as CommandService
    participant csRepo as Repository
    participant csDb as Postgres
    participant event as DomainEvent
    participant csetting as CustomerSettingController
    participant rb as Kafka
    participant nf as NotificationService




    c -) api: POST: {domain}/api/v1/customers <br> Edit
    Note left of c: { "FirstName": "New" <br> "LastName": "New" <br> "Gender": "Male" }
    api -) cs: navigate to CustomerService

    cs -) csCont: navigate to edit customer API

    csCont -) csServ: called to CommandService


    csServ -) csRepo: called to Repository
    csRepo -> csRepo: domain validate

    csRepo -) csDb: Save data
    
    csServ -)+ event: publish CustomerEdited event
    event -) csetting: publish to customer setting controller
    csetting -) csetting: create customer setting
    event -) -rb: pulish to Kafka
    csCont --) api: HTTP Status 201
    api --) c: recieved HTTP Status 201

    rb -) nf: consume CustomerEdited event
    nf -) nf: send to customer
    nf -) c: send notification