plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '6.25.0'
    id 'com.google.cloud.tools.jib' version '3.4.5'
//    id 'checkstyle'
}

group = 'mini.integration'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {

//    implementation 'mini.integration.lib:integration-lib:0.0.2'
    implementation group: 'io.github.dbunthai', name: 'mini-integration-lib', version: '0.1.3'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    compileOnly("org.mapstruct:mapstruct:1.6.3")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")

    implementation("com.googlecode.libphonenumber:libphonenumber:9.0.7")

    implementation("org.springframework.boot:spring-boot-starter-validation:3.5.0")
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'net.datafaker:datafaker:2.0.2'
    implementation 'org.springframework.kafka:spring-kafka'
    runtimeOnly 'org.liquibase:liquibase-core'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

spotless {
    java {
        target 'src/**/*.java'
        targetExclude 'build/**', 'src/test/**', 'src/generated/**'
        eclipse().configFile("eclipse-java-google-style.xml")
        trimTrailingWhitespace()
        endWithNewline()
    }
}

//checkstyle {
//    toolVersion = '10.12.2'
//    configFile = file("${rootDir}/checkstyle.xml")
//}
//
//checkstyleMain {
//    source = fileTree('.') {
//        excludes = ['.*/**', 'gradle*', 'build/**', '*.iml', '*.log', '**/*.jar']
//    }
//}

tasks.named('check') {
    dependsOn 'spotlessCheck'
//    , 'checkstyleMain'
}


jib {
    from {
        image = 'openjdk:21-jdk-slim'   // Base JDK runtime
    }
    to {
        image = 'customer-service'              // Default local image
        tags = [version, 'latest']
    }
    container {
        // Jib usually detects Spring Boot main class automatically
        ports = ['8080']                   // Expose HTTP port
        jvmFlags = [
                '-XX:+UseContainerSupport',
                '-XX:MaxRAMPercentage=75.0',
//                '-Duser.timezone=America/New_York',
                '-Dfile.encoding=UTF-8'
        ]
//        environment = [
//                'SPRING_PROFILES_ACTIVE': 'default'
//        ]
//        user = '65532:65532'               // Run as non-root
        labels = [
                'org.opencontainers.image.title'   : 'customer-service',
                'org.opencontainers.image.version' : version,
                'org.opencontainers.image.source'  : 'https://github.com/DBunthai/mini-integration',
                'org.opencontainers.image.licenses': 'Apache-2.0'
        ]
    }

    // If you want to copy configs/scripts into the container
    // extraDirectories {
    //     paths = file('src/main/jib')
    //     permissions = ['/scripts/start.sh': '755']
    // }
}